name: Lighthouse CI
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - name: Wait for Netlify
        uses: jakepartusch/wait-for-netlify-action@efd2dfc155ba297f1feb2153db990831ae4997d6
        id: netlify
        with:
          site_name: 'boring-benz-edfaa1'
      - run: npm i puppeteer
      - name: Lighthouse Desktop
        uses: treosh/lighthouse-ci-action@b8ccf8448921ddc6d53f5b8e218aa7c3f451b6b1
        id: lighthouse_audit_desktop
        with:
          configPath: ./.github/workflows/lighthouserc.js
          uploadArtifacts: ${{ !env.ACT }}
          temporaryPublicStorage: false
        env:
          BASE_URL:  ${{ steps.netlify.outputs.url }}
          LIGHTHOUSE_PRESET: desktop
      - name: Lighthouse Mobile
        uses: treosh/lighthouse-ci-action@b8ccf8448921ddc6d53f5b8e218aa7c3f451b6b1
        id: lighthouse_audit_mobile
        with:
          configPath: ./.github/workflows/lighthouserc.js
          uploadArtifacts: ${{ !env.ACT }} 
          temporaryPublicStorage: false
        env:
          BASE_URL:  ${{ steps.netlify.outputs.url }}
          LIGHTHOUSE_PRESET: mobile
      - name: Format Lighthouse Score
        id: format_lighthouse_score
        uses: actions/github-script@v4
        with:
          script: |
            const script = require('./.github/workflows/lighthouse-summary-report.js');
            const manifest = ${{ steps.lighthouse_audit_mobile.outputs.manifest }};

            script({manifest, core})
      - name: Add comment to PR
        id: comment_to_pr
        uses: marocchino/sticky-pull-request-comment@322a2451dae6c7831d1a8b931275a7f78147c888
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.issue.number }}
          header: lighthouse
          message: |
            ${{ steps.format_lighthouse_score.outputs.comment }}